# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_interrupt_system_3_gpios/zynq_interrupt_system_3_gpios.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_3_gpios || ORIG_REF_NAME==zynq_interrupt_system_3_gpios} -quiet] -quiet

# IP: bd/zynq_interrupt_system_3_gpios/ip/zynq_interrupt_system_3_gpios_axi_gpio_0_0/zynq_interrupt_system_3_gpios_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_3_gpios_axi_gpio_0_0 || ORIG_REF_NAME==zynq_interrupt_system_3_gpios_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq_interrupt_system_3_gpios/ip/zynq_interrupt_system_3_gpios_axi_gpio_1_0/zynq_interrupt_system_3_gpios_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_3_gpios_axi_gpio_1_0 || ORIG_REF_NAME==zynq_interrupt_system_3_gpios_axi_gpio_1_0} -quiet] -quiet

# IP: bd/zynq_interrupt_system_3_gpios/ip/zynq_interrupt_system_3_gpios_axi_timer_0_0/zynq_interrupt_system_3_gpios_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_3_gpios_axi_timer_0_0 || ORIG_REF_NAME==zynq_interrupt_system_3_gpios_axi_timer_0_0} -quiet] -quiet

# IP: bd/zynq_interrupt_system_3_gpios/ip/zynq_interrupt_system_3_gpios_processing_system7_0_0/zynq_interrupt_system_3_gpios_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_3_gpios_processing_system7_0_0 || ORIG_REF_NAME==zynq_interrupt_system_3_gpios_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_interrupt_system_3_gpios/ip/zynq_interrupt_system_3_gpios_xbar_0/zynq_interrupt_system_3_gpios_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_3_gpios_xbar_0 || ORIG_REF_NAME==zynq_interrupt_system_3_gpios_xbar_0} -quiet] -quiet

# IP: bd/zynq_interrupt_system_3_gpios/ip/zynq_interrupt_system_3_gpios_ps7_0_axi_periph_0/zynq_interrupt_system_3_gpios_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_3_gpios_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_interrupt_system_3_gpios_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_interrupt_system_3_gpios/ip/zynq_interrupt_system_3_gpios_rst_ps7_0_100M_0/zynq_interrupt_system_3_gpios_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_3_gpios_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_interrupt_system_3_gpios_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zynq_interrupt_system_3_gpios/ip/zynq_interrupt_system_3_gpios_xlconcat_0_0/zynq_interrupt_system_3_gpios_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_3_gpios_xlconcat_0_0 || ORIG_REF_NAME==zynq_interrupt_system_3_gpios_xlconcat_0_0} -quiet] -quiet

# IP: bd/zynq_interrupt_system_3_gpios/ip/zynq_interrupt_system_3_gpios_auto_pc_0/zynq_interrupt_system_3_gpios_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_3_gpios_auto_pc_0 || ORIG_REF_NAME==zynq_interrupt_system_3_gpios_auto_pc_0} -quiet] -quiet

# IP: bd/zynq_interrupt_system_3_gpios/ip/zynq_interrupt_system_3_gpios_axi_gpio_2_0/zynq_interrupt_system_3_gpios_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_interrupt_system_3_gpios_axi_gpio_2_0 || ORIG_REF_NAME==zynq_interrupt_system_3_gpios_axi_gpio_2_0} -quiet] -quiet

# XDC: bd/zynq_interrupt_system_3_gpios/zynq_interrupt_system_3_gpios_ooc.xdc
